[tool.pyright]

reportGeneralTypeIssues = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportUnknownMemberType = false

[tool.mypy]
exclude = [
    "tmp",
]

ignore_missing_imports = true

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]


[tool.ruff.lint.pydocstyle]
convention = "google"
